export const b1= {

    images:[
        "bg.png",
        "boy.png",
        "boy2.png",
        "car.png",
        "cloud.png",
        "cloud2.png",
        "girl.png",
        "girl2.png",
        "grass.png",
        "grass2.png",
        "grass3.png",
        "milkyWay.png",
        "moon.png",
        "owl.png",
        "star.png",
        "tree.png",
        "tree_1.png"
    ],
    sounds:[],
    json:[],
    videos:[],
    spine:[]

}

export const b2= {
    images:[
        "bg.png",
        "bear_doll.png",
        "blue_socks.png",
        "box.png",
        "box_1.png",
        "box_2.png",
        "boy.png",
        "corolla.png",
        "frame.png",
        "hat1.png",
        "hat2.png",
        "lighting1.png",
        "lighting2.png",
        "muffler1.png",
        "muffler2.png",
        "pie.png",
        "red_socks.png",
        "snowman.png",
        "star_b.png",
        "star_y.png",
        "tree.png"
    ],
    sounds:[],
    json:[],
    videos:[],
    spine:[]
}

export const b3= {
    images:[
        "bg.png",
        "ball.png",
        "bookcase.png",
        "boy.png",
        "candy.png",
        "chair.png",
        "clock.png",
        "clock_green.png",
        "dresser.png",
        "frame.png",
        "frame2.png",
        "lighting.png",
        "mouse.png",
        "mouse2.png",
        "speak.png",
        "telescope.png",
        "toy_car.png"
    ],
    sounds:[],
    json:[],
    videos:[],
    spine:[]
}

export const b4= {
    images:[
        "bg.png",
        "bush.png",
        "cow.png",
        "dish.png",
        "doghouse.png",
        "haha.png",
        "kitten.png",
        "kitten2.png",
        "moon.png",
        "puppy.png",
        "sleep.png",
        "sleep2.png",
        "spoon.png",
        "tree.png",
        "trunk.png",
        "violin.png",
        "weeds.png"
    ],
    sounds:[],
    json:[],
    videos:[],
    spine:[]
}

export const b5= {
    images:[
        "bg.png",
        "bell.png",
        "cloude.png",
        "gift1.png",
        "gift2.png",
        "green_elf.png",
        "hat_black.png",
        "hat_pink.png",
        "horse.png",
        "house.png",
        "muffler_g.png",
        "muffler_r.png",
        "red_elf.png",
        "santa.png",
        "sled.png",
        "snow.png",
        "tree_1.png",
        "tree_2.png",
        "tree_3.png"
    ],
    sounds:[],
    json:[],
    videos:[],
    spine:[]
}

export const b6= {
    images:[
        "bg.png",
        "audience1.png",
        "audience2.png",
        "baby.png",
        "brother.png",
        "curtain1.png",
        "curtain2.png",
        "curtain3.png",
        "curtain4.png",
        "daddy.png",
        "girl1.png",
        "girl2.png",
        "glitter.png",
        "mommy.png",
        "ribbon1.png",
        "ribbon2.png",
        "sister.png",
        "stage1.png",
        "stage2.png"
    ],
    sounds:[],
    json:[],
    videos:[],
    spine:[]
}

export const b7= {
    images:[
        "bg.png",
        "broccoli1.png",
        "broccoli2.png",
        "broccoli3.png",
        "broccoli4.png",
        "carrot1.png",
        "carrot2.png",
        "carrot3.png",
        "carrot4.png",
        "eggplant1.png",
        "eggplant2.png",
        "eggplant3.png",
        "eggplant4.png",
        "garlic1.png",
        "garlic2.png",
        "garlic3.png",
        "garlic4.png",
        "onion1.png",
        "onion2.png",
        "onion3.png",
        "onion4.png",
        "pear1.png",
        "pear2.png",
        "pear3.png",
        "pear4.png",
        "pineapple1.png",
        "pineapple2.png",
        "pineapple3.png",
        "pineapple4.png",
        "strawberry1.png",
        "strawberry2.png",
        "strawberry3.png",
        "strawberry4.png",
        "turnip1.png",
        "turnip2.png",
        "turnip3.png",
        "turnip4.png"
    ],
    sounds:[],
    json:[],
    videos:[],
    spine:[]
}

export const b8= {
    images:[
        "bg.png",
        "bag.png",
        "bed.png",
        "boy.png",
        "chiffonier.png",
        "clock.png",
        "closet.png",
        "cloud.png",
        "curtain.png",
        "dart.png",
        "fairy.png",
        "flowerpot.png",
        "light.png",
        "mirror.png",
        "moon.png",
        "poster.png",
        "rug.png",
        "soccer_ball.png",
        "spaceship.png",
        "star.png"
    ],
    sounds:[],
    json:[],
    videos:[],
    spine:[]
}

export const b9= {
    images:[
        "bg.png",
        "cloud1.png",
        "cloud2.png",
        "dog.png",
        "duck1.png",
        "duck2.png",
        "duck3.png",
        "farm.png",
        "farmer.png",
        "fence.png",
        "flower1.png",
        "flower2.png",
        "flower3.png",
        "girl.png",
        "grass1.png",
        "grass2.png",
        "horse.png",
        "milk_cow.png",
        "pig.png",
        "sheep.png",
        "tree1.png",
        "tree2.png",
        "tree3.png"
    ],
    sounds:[],
    json:[],
    videos:[],
    spine:[]
}

export const b10= {
    images:[
        "bg.png",
        "bus.png",
        "bus_stop.png",
        "bush.png",
        "cloud1.png",
        "cloud2.png",
        "curry_house.png",
        "grass1.png",
        "grass2.png",
        "house.png",
        "library.png",
        "pizzeria.png",
        "street_lamp.png",
        "traffic_light.png",
        "trash_can.png",
        "tree1.png",
        "tree2.png"
    ],
    sounds:[],
    json:[],
    videos:[],
    spine:[]
}